language: ruby
rvm:
  - 2.4.1

before_script:
 - chmod +x ./script/cibuild # or do this locally and commitc

git:
  depth: 25
  quiet: true
  
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default. 
script: ./script/cibuild

#deply to github
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local_dir: public
#  on:
#    branch: release1

# deploy to GCS
#deploy:
#  provider: gcs
#  access_key_id: $AKEY
#  secret_access_key: $ASEC
#  bucket: mhw_production
#  skip_cleanup: true
#  acl: public-read
#  local-dir: public

#after_success: s3_website push

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: "http://goldsmithd.github.io.s3-website.eu-west-2.amazonaws.com"
  skip_cleanup: true
  local_dir: public



addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
